package com.zsquant.flink.proto.compiled;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Derivative.proto

public final class Derivative {
  private Derivative() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TheoPriceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TheoPrice)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes exchange = 1;</code>
     * @return The exchange.
     */
    com.google.protobuf.ByteString getExchange();

    /**
     * <code>bytes instrument_id = 2;</code>
     * @return The instrumentId.
     */
    com.google.protobuf.ByteString getInstrumentId();

    /**
     * <code>double theo_price = 3;</code>
     * @return The theoPrice.
     */
    double getTheoPrice();
  }
  /**
   * <pre>
   * TheoPrice
   * </pre>
   *
   * Protobuf type {@code TheoPrice}
   */
  public static final class TheoPrice extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TheoPrice)
      TheoPriceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TheoPrice.newBuilder() to construct.
    private TheoPrice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TheoPrice() {
      exchange_ = com.google.protobuf.ByteString.EMPTY;
      instrumentId_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TheoPrice();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Derivative.internal_static_TheoPrice_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Derivative.internal_static_TheoPrice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Derivative.TheoPrice.class, Derivative.TheoPrice.Builder.class);
    }

    public static final int EXCHANGE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString exchange_;
    /**
     * <code>bytes exchange = 1;</code>
     * @return The exchange.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getExchange() {
      return exchange_;
    }

    public static final int INSTRUMENT_ID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString instrumentId_;
    /**
     * <code>bytes instrument_id = 2;</code>
     * @return The instrumentId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getInstrumentId() {
      return instrumentId_;
    }

    public static final int THEO_PRICE_FIELD_NUMBER = 3;
    private double theoPrice_;
    /**
     * <code>double theo_price = 3;</code>
     * @return The theoPrice.
     */
    @java.lang.Override
    public double getTheoPrice() {
      return theoPrice_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!exchange_.isEmpty()) {
        output.writeBytes(1, exchange_);
      }
      if (!instrumentId_.isEmpty()) {
        output.writeBytes(2, instrumentId_);
      }
      if (java.lang.Double.doubleToRawLongBits(theoPrice_) != 0) {
        output.writeDouble(3, theoPrice_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!exchange_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, exchange_);
      }
      if (!instrumentId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, instrumentId_);
      }
      if (java.lang.Double.doubleToRawLongBits(theoPrice_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, theoPrice_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Derivative.TheoPrice)) {
        return super.equals(obj);
      }
      Derivative.TheoPrice other = (Derivative.TheoPrice) obj;

      if (!getExchange()
          .equals(other.getExchange())) return false;
      if (!getInstrumentId()
          .equals(other.getInstrumentId())) return false;
      if (java.lang.Double.doubleToLongBits(getTheoPrice())
          != java.lang.Double.doubleToLongBits(
              other.getTheoPrice())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXCHANGE_FIELD_NUMBER;
      hash = (53 * hash) + getExchange().hashCode();
      hash = (37 * hash) + INSTRUMENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getInstrumentId().hashCode();
      hash = (37 * hash) + THEO_PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTheoPrice()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Derivative.TheoPrice parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Derivative.TheoPrice parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Derivative.TheoPrice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Derivative.TheoPrice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Derivative.TheoPrice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Derivative.TheoPrice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Derivative.TheoPrice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Derivative.TheoPrice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Derivative.TheoPrice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Derivative.TheoPrice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Derivative.TheoPrice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Derivative.TheoPrice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Derivative.TheoPrice prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * TheoPrice
     * </pre>
     *
     * Protobuf type {@code TheoPrice}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TheoPrice)
        Derivative.TheoPriceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Derivative.internal_static_TheoPrice_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Derivative.internal_static_TheoPrice_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Derivative.TheoPrice.class, Derivative.TheoPrice.Builder.class);
      }

      // Construct using Derivative.TheoPrice.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        exchange_ = com.google.protobuf.ByteString.EMPTY;

        instrumentId_ = com.google.protobuf.ByteString.EMPTY;

        theoPrice_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Derivative.internal_static_TheoPrice_descriptor;
      }

      @java.lang.Override
      public Derivative.TheoPrice getDefaultInstanceForType() {
        return Derivative.TheoPrice.getDefaultInstance();
      }

      @java.lang.Override
      public Derivative.TheoPrice build() {
        Derivative.TheoPrice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Derivative.TheoPrice buildPartial() {
        Derivative.TheoPrice result = new Derivative.TheoPrice(this);
        result.exchange_ = exchange_;
        result.instrumentId_ = instrumentId_;
        result.theoPrice_ = theoPrice_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Derivative.TheoPrice) {
          return mergeFrom((Derivative.TheoPrice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Derivative.TheoPrice other) {
        if (other == Derivative.TheoPrice.getDefaultInstance()) return this;
        if (other.getExchange() != com.google.protobuf.ByteString.EMPTY) {
          setExchange(other.getExchange());
        }
        if (other.getInstrumentId() != com.google.protobuf.ByteString.EMPTY) {
          setInstrumentId(other.getInstrumentId());
        }
        if (other.getTheoPrice() != 0D) {
          setTheoPrice(other.getTheoPrice());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                exchange_ = input.readBytes();

                break;
              } // case 10
              case 18: {
                instrumentId_ = input.readBytes();

                break;
              } // case 18
              case 25: {
                theoPrice_ = input.readDouble();

                break;
              } // case 25
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private com.google.protobuf.ByteString exchange_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes exchange = 1;</code>
       * @return The exchange.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getExchange() {
        return exchange_;
      }
      /**
       * <code>bytes exchange = 1;</code>
       * @param value The exchange to set.
       * @return This builder for chaining.
       */
      public Builder setExchange(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        exchange_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes exchange = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearExchange() {
        
        exchange_ = getDefaultInstance().getExchange();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString instrumentId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes instrument_id = 2;</code>
       * @return The instrumentId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getInstrumentId() {
        return instrumentId_;
      }
      /**
       * <code>bytes instrument_id = 2;</code>
       * @param value The instrumentId to set.
       * @return This builder for chaining.
       */
      public Builder setInstrumentId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        instrumentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes instrument_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearInstrumentId() {
        
        instrumentId_ = getDefaultInstance().getInstrumentId();
        onChanged();
        return this;
      }

      private double theoPrice_ ;
      /**
       * <code>double theo_price = 3;</code>
       * @return The theoPrice.
       */
      @java.lang.Override
      public double getTheoPrice() {
        return theoPrice_;
      }
      /**
       * <code>double theo_price = 3;</code>
       * @param value The theoPrice to set.
       * @return This builder for chaining.
       */
      public Builder setTheoPrice(double value) {
        
        theoPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double theo_price = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTheoPrice() {
        
        theoPrice_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TheoPrice)
    }

    // @@protoc_insertion_point(class_scope:TheoPrice)
    private static final Derivative.TheoPrice DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Derivative.TheoPrice();
    }

    public static Derivative.TheoPrice getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TheoPrice>
        PARSER = new com.google.protobuf.AbstractParser<TheoPrice>() {
      @java.lang.Override
      public TheoPrice parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TheoPrice> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TheoPrice> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Derivative.TheoPrice getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OptionPricingRstOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OptionPricingRst)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes exchange = 1;</code>
     * @return The exchange.
     */
    com.google.protobuf.ByteString getExchange();

    /**
     * <code>bytes instrument_id = 2;</code>
     * @return The instrumentId.
     */
    com.google.protobuf.ByteString getInstrumentId();

    /**
     * <code>double fair_value = 3;</code>
     * @return The fairValue.
     */
    double getFairValue();

    /**
     * <code>double delta = 4;</code>
     * @return The delta.
     */
    double getDelta();
  }
  /**
   * <pre>
   * OptionPricinaRst
   * </pre>
   *
   * Protobuf type {@code OptionPricingRst}
   */
  public static final class OptionPricingRst extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OptionPricingRst)
      OptionPricingRstOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OptionPricingRst.newBuilder() to construct.
    private OptionPricingRst(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OptionPricingRst() {
      exchange_ = com.google.protobuf.ByteString.EMPTY;
      instrumentId_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OptionPricingRst();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Derivative.internal_static_OptionPricingRst_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Derivative.internal_static_OptionPricingRst_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Derivative.OptionPricingRst.class, Derivative.OptionPricingRst.Builder.class);
    }

    public static final int EXCHANGE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString exchange_;
    /**
     * <code>bytes exchange = 1;</code>
     * @return The exchange.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getExchange() {
      return exchange_;
    }

    public static final int INSTRUMENT_ID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString instrumentId_;
    /**
     * <code>bytes instrument_id = 2;</code>
     * @return The instrumentId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getInstrumentId() {
      return instrumentId_;
    }

    public static final int FAIR_VALUE_FIELD_NUMBER = 3;
    private double fairValue_;
    /**
     * <code>double fair_value = 3;</code>
     * @return The fairValue.
     */
    @java.lang.Override
    public double getFairValue() {
      return fairValue_;
    }

    public static final int DELTA_FIELD_NUMBER = 4;
    private double delta_;
    /**
     * <code>double delta = 4;</code>
     * @return The delta.
     */
    @java.lang.Override
    public double getDelta() {
      return delta_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!exchange_.isEmpty()) {
        output.writeBytes(1, exchange_);
      }
      if (!instrumentId_.isEmpty()) {
        output.writeBytes(2, instrumentId_);
      }
      if (java.lang.Double.doubleToRawLongBits(fairValue_) != 0) {
        output.writeDouble(3, fairValue_);
      }
      if (java.lang.Double.doubleToRawLongBits(delta_) != 0) {
        output.writeDouble(4, delta_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!exchange_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, exchange_);
      }
      if (!instrumentId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, instrumentId_);
      }
      if (java.lang.Double.doubleToRawLongBits(fairValue_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, fairValue_);
      }
      if (java.lang.Double.doubleToRawLongBits(delta_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, delta_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Derivative.OptionPricingRst)) {
        return super.equals(obj);
      }
      Derivative.OptionPricingRst other = (Derivative.OptionPricingRst) obj;

      if (!getExchange()
          .equals(other.getExchange())) return false;
      if (!getInstrumentId()
          .equals(other.getInstrumentId())) return false;
      if (java.lang.Double.doubleToLongBits(getFairValue())
          != java.lang.Double.doubleToLongBits(
              other.getFairValue())) return false;
      if (java.lang.Double.doubleToLongBits(getDelta())
          != java.lang.Double.doubleToLongBits(
              other.getDelta())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXCHANGE_FIELD_NUMBER;
      hash = (53 * hash) + getExchange().hashCode();
      hash = (37 * hash) + INSTRUMENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getInstrumentId().hashCode();
      hash = (37 * hash) + FAIR_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getFairValue()));
      hash = (37 * hash) + DELTA_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDelta()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Derivative.OptionPricingRst parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Derivative.OptionPricingRst parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Derivative.OptionPricingRst parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Derivative.OptionPricingRst parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Derivative.OptionPricingRst parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Derivative.OptionPricingRst parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Derivative.OptionPricingRst parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Derivative.OptionPricingRst parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Derivative.OptionPricingRst parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Derivative.OptionPricingRst parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Derivative.OptionPricingRst parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Derivative.OptionPricingRst parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Derivative.OptionPricingRst prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * OptionPricinaRst
     * </pre>
     *
     * Protobuf type {@code OptionPricingRst}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OptionPricingRst)
        Derivative.OptionPricingRstOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Derivative.internal_static_OptionPricingRst_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Derivative.internal_static_OptionPricingRst_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Derivative.OptionPricingRst.class, Derivative.OptionPricingRst.Builder.class);
      }

      // Construct using Derivative.OptionPricingRst.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        exchange_ = com.google.protobuf.ByteString.EMPTY;

        instrumentId_ = com.google.protobuf.ByteString.EMPTY;

        fairValue_ = 0D;

        delta_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Derivative.internal_static_OptionPricingRst_descriptor;
      }

      @java.lang.Override
      public Derivative.OptionPricingRst getDefaultInstanceForType() {
        return Derivative.OptionPricingRst.getDefaultInstance();
      }

      @java.lang.Override
      public Derivative.OptionPricingRst build() {
        Derivative.OptionPricingRst result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Derivative.OptionPricingRst buildPartial() {
        Derivative.OptionPricingRst result = new Derivative.OptionPricingRst(this);
        result.exchange_ = exchange_;
        result.instrumentId_ = instrumentId_;
        result.fairValue_ = fairValue_;
        result.delta_ = delta_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Derivative.OptionPricingRst) {
          return mergeFrom((Derivative.OptionPricingRst)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Derivative.OptionPricingRst other) {
        if (other == Derivative.OptionPricingRst.getDefaultInstance()) return this;
        if (other.getExchange() != com.google.protobuf.ByteString.EMPTY) {
          setExchange(other.getExchange());
        }
        if (other.getInstrumentId() != com.google.protobuf.ByteString.EMPTY) {
          setInstrumentId(other.getInstrumentId());
        }
        if (other.getFairValue() != 0D) {
          setFairValue(other.getFairValue());
        }
        if (other.getDelta() != 0D) {
          setDelta(other.getDelta());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                exchange_ = input.readBytes();

                break;
              } // case 10
              case 18: {
                instrumentId_ = input.readBytes();

                break;
              } // case 18
              case 25: {
                fairValue_ = input.readDouble();

                break;
              } // case 25
              case 33: {
                delta_ = input.readDouble();

                break;
              } // case 33
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private com.google.protobuf.ByteString exchange_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes exchange = 1;</code>
       * @return The exchange.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getExchange() {
        return exchange_;
      }
      /**
       * <code>bytes exchange = 1;</code>
       * @param value The exchange to set.
       * @return This builder for chaining.
       */
      public Builder setExchange(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        exchange_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes exchange = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearExchange() {
        
        exchange_ = getDefaultInstance().getExchange();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString instrumentId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes instrument_id = 2;</code>
       * @return The instrumentId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getInstrumentId() {
        return instrumentId_;
      }
      /**
       * <code>bytes instrument_id = 2;</code>
       * @param value The instrumentId to set.
       * @return This builder for chaining.
       */
      public Builder setInstrumentId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        instrumentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes instrument_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearInstrumentId() {
        
        instrumentId_ = getDefaultInstance().getInstrumentId();
        onChanged();
        return this;
      }

      private double fairValue_ ;
      /**
       * <code>double fair_value = 3;</code>
       * @return The fairValue.
       */
      @java.lang.Override
      public double getFairValue() {
        return fairValue_;
      }
      /**
       * <code>double fair_value = 3;</code>
       * @param value The fairValue to set.
       * @return This builder for chaining.
       */
      public Builder setFairValue(double value) {
        
        fairValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double fair_value = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFairValue() {
        
        fairValue_ = 0D;
        onChanged();
        return this;
      }

      private double delta_ ;
      /**
       * <code>double delta = 4;</code>
       * @return The delta.
       */
      @java.lang.Override
      public double getDelta() {
        return delta_;
      }
      /**
       * <code>double delta = 4;</code>
       * @param value The delta to set.
       * @return This builder for chaining.
       */
      public Builder setDelta(double value) {
        
        delta_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double delta = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDelta() {
        
        delta_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OptionPricingRst)
    }

    // @@protoc_insertion_point(class_scope:OptionPricingRst)
    private static final Derivative.OptionPricingRst DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Derivative.OptionPricingRst();
    }

    public static Derivative.OptionPricingRst getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OptionPricingRst>
        PARSER = new com.google.protobuf.AbstractParser<OptionPricingRst>() {
      @java.lang.Override
      public OptionPricingRst parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OptionPricingRst> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OptionPricingRst> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Derivative.OptionPricingRst getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Event)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>fixed64 produce_time = 1;</code>
     * @return The produceTime.
     */
    long getProduceTime();

    /**
     * <code>.TheoPrice theo_price = 10;</code>
     * @return Whether the theoPrice field is set.
     */
    boolean hasTheoPrice();
    /**
     * <code>.TheoPrice theo_price = 10;</code>
     * @return The theoPrice.
     */
    Derivative.TheoPrice getTheoPrice();
    /**
     * <code>.TheoPrice theo_price = 10;</code>
     */
    Derivative.TheoPriceOrBuilder getTheoPriceOrBuilder();

    /**
     * <code>.OptionPricingRst option_pricing_rst = 11;</code>
     * @return Whether the optionPricingRst field is set.
     */
    boolean hasOptionPricingRst();
    /**
     * <code>.OptionPricingRst option_pricing_rst = 11;</code>
     * @return The optionPricingRst.
     */
    Derivative.OptionPricingRst getOptionPricingRst();
    /**
     * <code>.OptionPricingRst option_pricing_rst = 11;</code>
     */
    Derivative.OptionPricingRstOrBuilder getOptionPricingRstOrBuilder();

    public Derivative.Event.ValueCase getValueCase();
  }
  /**
   * Protobuf type {@code Event}
   */
  public static final class Event extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Event)
      EventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Event.newBuilder() to construct.
    private Event(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Event() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Event();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Derivative.internal_static_Event_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Derivative.internal_static_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Derivative.Event.class, Derivative.Event.Builder.class);
    }

    private int valueCase_ = 0;
    private java.lang.Object value_;
    public enum ValueCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      THEO_PRICE(10),
      OPTION_PRICING_RST(11),
      VALUE_NOT_SET(0);
      private final int value;
      private ValueCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ValueCase valueOf(int value) {
        return forNumber(value);
      }

      public static ValueCase forNumber(int value) {
        switch (value) {
          case 10: return THEO_PRICE;
          case 11: return OPTION_PRICING_RST;
          case 0: return VALUE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ValueCase
    getValueCase() {
      return ValueCase.forNumber(
          valueCase_);
    }

    public static final int PRODUCE_TIME_FIELD_NUMBER = 1;
    private long produceTime_;
    /**
     * <code>fixed64 produce_time = 1;</code>
     * @return The produceTime.
     */
    @java.lang.Override
    public long getProduceTime() {
      return produceTime_;
    }

    public static final int THEO_PRICE_FIELD_NUMBER = 10;
    /**
     * <code>.TheoPrice theo_price = 10;</code>
     * @return Whether the theoPrice field is set.
     */
    @java.lang.Override
    public boolean hasTheoPrice() {
      return valueCase_ == 10;
    }
    /**
     * <code>.TheoPrice theo_price = 10;</code>
     * @return The theoPrice.
     */
    @java.lang.Override
    public Derivative.TheoPrice getTheoPrice() {
      if (valueCase_ == 10) {
         return (Derivative.TheoPrice) value_;
      }
      return Derivative.TheoPrice.getDefaultInstance();
    }
    /**
     * <code>.TheoPrice theo_price = 10;</code>
     */
    @java.lang.Override
    public Derivative.TheoPriceOrBuilder getTheoPriceOrBuilder() {
      if (valueCase_ == 10) {
         return (Derivative.TheoPrice) value_;
      }
      return Derivative.TheoPrice.getDefaultInstance();
    }

    public static final int OPTION_PRICING_RST_FIELD_NUMBER = 11;
    /**
     * <code>.OptionPricingRst option_pricing_rst = 11;</code>
     * @return Whether the optionPricingRst field is set.
     */
    @java.lang.Override
    public boolean hasOptionPricingRst() {
      return valueCase_ == 11;
    }
    /**
     * <code>.OptionPricingRst option_pricing_rst = 11;</code>
     * @return The optionPricingRst.
     */
    @java.lang.Override
    public Derivative.OptionPricingRst getOptionPricingRst() {
      if (valueCase_ == 11) {
         return (Derivative.OptionPricingRst) value_;
      }
      return Derivative.OptionPricingRst.getDefaultInstance();
    }
    /**
     * <code>.OptionPricingRst option_pricing_rst = 11;</code>
     */
    @java.lang.Override
    public Derivative.OptionPricingRstOrBuilder getOptionPricingRstOrBuilder() {
      if (valueCase_ == 11) {
         return (Derivative.OptionPricingRst) value_;
      }
      return Derivative.OptionPricingRst.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (produceTime_ != 0L) {
        output.writeFixed64(1, produceTime_);
      }
      if (valueCase_ == 10) {
        output.writeMessage(10, (Derivative.TheoPrice) value_);
      }
      if (valueCase_ == 11) {
        output.writeMessage(11, (Derivative.OptionPricingRst) value_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (produceTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(1, produceTime_);
      }
      if (valueCase_ == 10) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, (Derivative.TheoPrice) value_);
      }
      if (valueCase_ == 11) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, (Derivative.OptionPricingRst) value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Derivative.Event)) {
        return super.equals(obj);
      }
      Derivative.Event other = (Derivative.Event) obj;

      if (getProduceTime()
          != other.getProduceTime()) return false;
      if (!getValueCase().equals(other.getValueCase())) return false;
      switch (valueCase_) {
        case 10:
          if (!getTheoPrice()
              .equals(other.getTheoPrice())) return false;
          break;
        case 11:
          if (!getOptionPricingRst()
              .equals(other.getOptionPricingRst())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRODUCE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProduceTime());
      switch (valueCase_) {
        case 10:
          hash = (37 * hash) + THEO_PRICE_FIELD_NUMBER;
          hash = (53 * hash) + getTheoPrice().hashCode();
          break;
        case 11:
          hash = (37 * hash) + OPTION_PRICING_RST_FIELD_NUMBER;
          hash = (53 * hash) + getOptionPricingRst().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Derivative.Event parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Derivative.Event parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Derivative.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Derivative.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Derivative.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Derivative.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Derivative.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Derivative.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Derivative.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Derivative.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Derivative.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Derivative.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Derivative.Event prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Event)
        Derivative.EventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Derivative.internal_static_Event_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Derivative.internal_static_Event_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Derivative.Event.class, Derivative.Event.Builder.class);
      }

      // Construct using Derivative.Event.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        produceTime_ = 0L;

        if (theoPriceBuilder_ != null) {
          theoPriceBuilder_.clear();
        }
        if (optionPricingRstBuilder_ != null) {
          optionPricingRstBuilder_.clear();
        }
        valueCase_ = 0;
        value_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Derivative.internal_static_Event_descriptor;
      }

      @java.lang.Override
      public Derivative.Event getDefaultInstanceForType() {
        return Derivative.Event.getDefaultInstance();
      }

      @java.lang.Override
      public Derivative.Event build() {
        Derivative.Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Derivative.Event buildPartial() {
        Derivative.Event result = new Derivative.Event(this);
        result.produceTime_ = produceTime_;
        if (valueCase_ == 10) {
          if (theoPriceBuilder_ == null) {
            result.value_ = value_;
          } else {
            result.value_ = theoPriceBuilder_.build();
          }
        }
        if (valueCase_ == 11) {
          if (optionPricingRstBuilder_ == null) {
            result.value_ = value_;
          } else {
            result.value_ = optionPricingRstBuilder_.build();
          }
        }
        result.valueCase_ = valueCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Derivative.Event) {
          return mergeFrom((Derivative.Event)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Derivative.Event other) {
        if (other == Derivative.Event.getDefaultInstance()) return this;
        if (other.getProduceTime() != 0L) {
          setProduceTime(other.getProduceTime());
        }
        switch (other.getValueCase()) {
          case THEO_PRICE: {
            mergeTheoPrice(other.getTheoPrice());
            break;
          }
          case OPTION_PRICING_RST: {
            mergeOptionPricingRst(other.getOptionPricingRst());
            break;
          }
          case VALUE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                produceTime_ = input.readFixed64();

                break;
              } // case 9
              case 82: {
                input.readMessage(
                    getTheoPriceFieldBuilder().getBuilder(),
                    extensionRegistry);
                valueCase_ = 10;
                break;
              } // case 82
              case 90: {
                input.readMessage(
                    getOptionPricingRstFieldBuilder().getBuilder(),
                    extensionRegistry);
                valueCase_ = 11;
                break;
              } // case 90
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int valueCase_ = 0;
      private java.lang.Object value_;
      public ValueCase
          getValueCase() {
        return ValueCase.forNumber(
            valueCase_);
      }

      public Builder clearValue() {
        valueCase_ = 0;
        value_ = null;
        onChanged();
        return this;
      }


      private long produceTime_ ;
      /**
       * <code>fixed64 produce_time = 1;</code>
       * @return The produceTime.
       */
      @java.lang.Override
      public long getProduceTime() {
        return produceTime_;
      }
      /**
       * <code>fixed64 produce_time = 1;</code>
       * @param value The produceTime to set.
       * @return This builder for chaining.
       */
      public Builder setProduceTime(long value) {
        
        produceTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed64 produce_time = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProduceTime() {
        
        produceTime_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Derivative.TheoPrice, Derivative.TheoPrice.Builder, Derivative.TheoPriceOrBuilder> theoPriceBuilder_;
      /**
       * <code>.TheoPrice theo_price = 10;</code>
       * @return Whether the theoPrice field is set.
       */
      @java.lang.Override
      public boolean hasTheoPrice() {
        return valueCase_ == 10;
      }
      /**
       * <code>.TheoPrice theo_price = 10;</code>
       * @return The theoPrice.
       */
      @java.lang.Override
      public Derivative.TheoPrice getTheoPrice() {
        if (theoPriceBuilder_ == null) {
          if (valueCase_ == 10) {
            return (Derivative.TheoPrice) value_;
          }
          return Derivative.TheoPrice.getDefaultInstance();
        } else {
          if (valueCase_ == 10) {
            return theoPriceBuilder_.getMessage();
          }
          return Derivative.TheoPrice.getDefaultInstance();
        }
      }
      /**
       * <code>.TheoPrice theo_price = 10;</code>
       */
      public Builder setTheoPrice(Derivative.TheoPrice value) {
        if (theoPriceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          theoPriceBuilder_.setMessage(value);
        }
        valueCase_ = 10;
        return this;
      }
      /**
       * <code>.TheoPrice theo_price = 10;</code>
       */
      public Builder setTheoPrice(
          Derivative.TheoPrice.Builder builderForValue) {
        if (theoPriceBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          theoPriceBuilder_.setMessage(builderForValue.build());
        }
        valueCase_ = 10;
        return this;
      }
      /**
       * <code>.TheoPrice theo_price = 10;</code>
       */
      public Builder mergeTheoPrice(Derivative.TheoPrice value) {
        if (theoPriceBuilder_ == null) {
          if (valueCase_ == 10 &&
              value_ != Derivative.TheoPrice.getDefaultInstance()) {
            value_ = Derivative.TheoPrice.newBuilder((Derivative.TheoPrice) value_)
                .mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          if (valueCase_ == 10) {
            theoPriceBuilder_.mergeFrom(value);
          } else {
            theoPriceBuilder_.setMessage(value);
          }
        }
        valueCase_ = 10;
        return this;
      }
      /**
       * <code>.TheoPrice theo_price = 10;</code>
       */
      public Builder clearTheoPrice() {
        if (theoPriceBuilder_ == null) {
          if (valueCase_ == 10) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
        } else {
          if (valueCase_ == 10) {
            valueCase_ = 0;
            value_ = null;
          }
          theoPriceBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.TheoPrice theo_price = 10;</code>
       */
      public Derivative.TheoPrice.Builder getTheoPriceBuilder() {
        return getTheoPriceFieldBuilder().getBuilder();
      }
      /**
       * <code>.TheoPrice theo_price = 10;</code>
       */
      @java.lang.Override
      public Derivative.TheoPriceOrBuilder getTheoPriceOrBuilder() {
        if ((valueCase_ == 10) && (theoPriceBuilder_ != null)) {
          return theoPriceBuilder_.getMessageOrBuilder();
        } else {
          if (valueCase_ == 10) {
            return (Derivative.TheoPrice) value_;
          }
          return Derivative.TheoPrice.getDefaultInstance();
        }
      }
      /**
       * <code>.TheoPrice theo_price = 10;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Derivative.TheoPrice, Derivative.TheoPrice.Builder, Derivative.TheoPriceOrBuilder> 
          getTheoPriceFieldBuilder() {
        if (theoPriceBuilder_ == null) {
          if (!(valueCase_ == 10)) {
            value_ = Derivative.TheoPrice.getDefaultInstance();
          }
          theoPriceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Derivative.TheoPrice, Derivative.TheoPrice.Builder, Derivative.TheoPriceOrBuilder>(
                  (Derivative.TheoPrice) value_,
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        valueCase_ = 10;
        onChanged();;
        return theoPriceBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Derivative.OptionPricingRst, Derivative.OptionPricingRst.Builder, Derivative.OptionPricingRstOrBuilder> optionPricingRstBuilder_;
      /**
       * <code>.OptionPricingRst option_pricing_rst = 11;</code>
       * @return Whether the optionPricingRst field is set.
       */
      @java.lang.Override
      public boolean hasOptionPricingRst() {
        return valueCase_ == 11;
      }
      /**
       * <code>.OptionPricingRst option_pricing_rst = 11;</code>
       * @return The optionPricingRst.
       */
      @java.lang.Override
      public Derivative.OptionPricingRst getOptionPricingRst() {
        if (optionPricingRstBuilder_ == null) {
          if (valueCase_ == 11) {
            return (Derivative.OptionPricingRst) value_;
          }
          return Derivative.OptionPricingRst.getDefaultInstance();
        } else {
          if (valueCase_ == 11) {
            return optionPricingRstBuilder_.getMessage();
          }
          return Derivative.OptionPricingRst.getDefaultInstance();
        }
      }
      /**
       * <code>.OptionPricingRst option_pricing_rst = 11;</code>
       */
      public Builder setOptionPricingRst(Derivative.OptionPricingRst value) {
        if (optionPricingRstBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          optionPricingRstBuilder_.setMessage(value);
        }
        valueCase_ = 11;
        return this;
      }
      /**
       * <code>.OptionPricingRst option_pricing_rst = 11;</code>
       */
      public Builder setOptionPricingRst(
          Derivative.OptionPricingRst.Builder builderForValue) {
        if (optionPricingRstBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          optionPricingRstBuilder_.setMessage(builderForValue.build());
        }
        valueCase_ = 11;
        return this;
      }
      /**
       * <code>.OptionPricingRst option_pricing_rst = 11;</code>
       */
      public Builder mergeOptionPricingRst(Derivative.OptionPricingRst value) {
        if (optionPricingRstBuilder_ == null) {
          if (valueCase_ == 11 &&
              value_ != Derivative.OptionPricingRst.getDefaultInstance()) {
            value_ = Derivative.OptionPricingRst.newBuilder((Derivative.OptionPricingRst) value_)
                .mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          if (valueCase_ == 11) {
            optionPricingRstBuilder_.mergeFrom(value);
          } else {
            optionPricingRstBuilder_.setMessage(value);
          }
        }
        valueCase_ = 11;
        return this;
      }
      /**
       * <code>.OptionPricingRst option_pricing_rst = 11;</code>
       */
      public Builder clearOptionPricingRst() {
        if (optionPricingRstBuilder_ == null) {
          if (valueCase_ == 11) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
        } else {
          if (valueCase_ == 11) {
            valueCase_ = 0;
            value_ = null;
          }
          optionPricingRstBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.OptionPricingRst option_pricing_rst = 11;</code>
       */
      public Derivative.OptionPricingRst.Builder getOptionPricingRstBuilder() {
        return getOptionPricingRstFieldBuilder().getBuilder();
      }
      /**
       * <code>.OptionPricingRst option_pricing_rst = 11;</code>
       */
      @java.lang.Override
      public Derivative.OptionPricingRstOrBuilder getOptionPricingRstOrBuilder() {
        if ((valueCase_ == 11) && (optionPricingRstBuilder_ != null)) {
          return optionPricingRstBuilder_.getMessageOrBuilder();
        } else {
          if (valueCase_ == 11) {
            return (Derivative.OptionPricingRst) value_;
          }
          return Derivative.OptionPricingRst.getDefaultInstance();
        }
      }
      /**
       * <code>.OptionPricingRst option_pricing_rst = 11;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Derivative.OptionPricingRst, Derivative.OptionPricingRst.Builder, Derivative.OptionPricingRstOrBuilder> 
          getOptionPricingRstFieldBuilder() {
        if (optionPricingRstBuilder_ == null) {
          if (!(valueCase_ == 11)) {
            value_ = Derivative.OptionPricingRst.getDefaultInstance();
          }
          optionPricingRstBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Derivative.OptionPricingRst, Derivative.OptionPricingRst.Builder, Derivative.OptionPricingRstOrBuilder>(
                  (Derivative.OptionPricingRst) value_,
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        valueCase_ = 11;
        onChanged();;
        return optionPricingRstBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Event)
    }

    // @@protoc_insertion_point(class_scope:Event)
    private static final Derivative.Event DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Derivative.Event();
    }

    public static Derivative.Event getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Event>
        PARSER = new com.google.protobuf.AbstractParser<Event>() {
      @java.lang.Override
      public Event parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Event> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Event> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Derivative.Event getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TheoPrice_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TheoPrice_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OptionPricingRst_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OptionPricingRst_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Event_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Event_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Derivative.proto\"H\n\tTheoPrice\022\020\n\010excha" +
      "nge\030\001 \001(\014\022\025\n\rinstrument_id\030\002 \001(\014\022\022\n\ntheo" +
      "_price\030\003 \001(\001\"^\n\020OptionPricingRst\022\020\n\010exch" +
      "ange\030\001 \001(\014\022\025\n\rinstrument_id\030\002 \001(\014\022\022\n\nfai" +
      "r_value\030\003 \001(\001\022\r\n\005delta\030\004 \001(\001\"y\n\005Event\022\024\n" +
      "\014produce_time\030\001 \001(\006\022 \n\ntheo_price\030\n \001(\0132" +
      "\n.TheoPriceH\000\022/\n\022option_pricing_rst\030\013 \001(" +
      "\0132\021.OptionPricingRstH\000B\007\n\005valueb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TheoPrice_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TheoPrice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TheoPrice_descriptor,
        new java.lang.String[] { "Exchange", "InstrumentId", "TheoPrice", });
    internal_static_OptionPricingRst_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OptionPricingRst_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OptionPricingRst_descriptor,
        new java.lang.String[] { "Exchange", "InstrumentId", "FairValue", "Delta", });
    internal_static_Event_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Event_descriptor,
        new java.lang.String[] { "ProduceTime", "TheoPrice", "OptionPricingRst", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
